def tweets():
    return [
        {'created_at': 'Fri Sep 16 09:14:47 +0000 2016', 'id': 776710916700340224, 'id_str': '776710916700340224',
         'text': 'The only thing worse than a political insider is the sort of candidate you get when people use their vote to protest against insiders.',
         'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': []},
         'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
         'in_reply_to_status_id': 776709936487235584, 'in_reply_to_status_id_str': '776709936487235584',
         'in_reply_to_user_id': 183749519, 'in_reply_to_user_id_str': '183749519',
         'in_reply_to_screen_name': 'paulg',
         'user': {'id': 183749519, 'id_str': '183749519', 'name': 'Paul Graham', 'screen_name': 'paulg',
                  'location': '', 'description': '', 'url': 'http://t.co/fDpOM1QB6e', 'entities': {'url': {'urls': [
                 {'url': 'http://t.co/fDpOM1QB6e', 'expanded_url': 'http://paulgraham.com',
                  'display_url': 'paulgraham.com', 'indices': [0, 22]}]}, 'description': {'urls': []}},
                  'protected': False, 'followers_count': 381800, 'friends_count': 232, 'listed_count': 8623,
                  'created_at': 'Fri Aug 27 20:13:59 +0000 2010', 'favourites_count': 2111, 'utc_offset': -25200,
                  'time_zone': 'Pacific Time (US & Canada)', 'geo_enabled': False, 'verified': True,
                  'statuses_count': 7737, 'lang': 'en', 'contributors_enabled': False, 'is_translator': False,
                  'is_translation_enabled': False, 'profile_background_color': 'ECD078',
                  'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/141294818/xf96365f8ddfaff01d0e2405faf5aaeb.png',
                  'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/141294818/xf96365f8ddfaff01d0e2405faf5aaeb.png',
                  'profile_background_tile': True,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/1824002576/pg-railsconf_normal.jpg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1824002576/pg-railsconf_normal.jpg',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/183749519/1401332683',
                  'profile_link_color': 'BA0013', 'profile_sidebar_border_color': 'FFFFFF',
                  'profile_sidebar_fill_color': '542437', 'profile_text_color': 'DD5036',
                  'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': False,
                  'default_profile_image': False, 'following': True, 'follow_request_sent': False,
                  'notifications': False}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
         'is_quote_status': False, 'retweet_count': 5, 'favorite_count': 8, 'favorited': False, 'retweeted': False,
         'lang': 'en'},
        {'created_at': 'Fri Sep 16 09:12:31 +0000 2016', 'id': 776710345499021312, 'id_str': '776710345499021312',
         'text': 'RT @Marion_Demos: Les nouvelles utopies managériales https://t.co/NJtn5ISY5l via @HubertLandier https://t.co/9kX6sQKwzi RT @Geuze_F',
         'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [
            {'screen_name': 'Marion_Demos', 'name': 'Marion de Demos', 'id': 93874450, 'id_str': '93874450',
             'indices': [3, 16]},
            {'screen_name': 'HubertLandier', 'name': 'Hubert Landier', 'id': 2799634401, 'id_str': '2799634401',
             'indices': [81, 95]},
            {'screen_name': 'Geuze_F', 'name': 'François GEUZE', 'id': 592843104, 'id_str': '592843104',
             'indices': [123, 131]}], 'urls': [{'url': 'https://t.co/NJtn5ISY5l',
                                                'expanded_url': 'http://www.e-rh.org/index.php/blogs/les-articles-du-blog/261-les-nouvelles-utopies-manageriales',
                                                'display_url': 'e-rh.org/index.php/blog…', 'indices': [53, 76]}],
                                          'media': [{'id': 775413458833637376, 'id_str': '775413458833637376',
                                                     'indices': [96, 119],
                                                     'media_url': 'http://pbs.twimg.com/media/CsLSbrfWAAAfFS0.jpg',
                                                     'media_url_https': 'https://pbs.twimg.com/media/CsLSbrfWAAAfFS0.jpg',
                                                     'url': 'https://t.co/9kX6sQKwzi',
                                                     'display_url': 'pic.twitter.com/9kX6sQKwzi',
                                                     'expanded_url': 'https://twitter.com/Geuze_F/status/775413462788874240/photo/1',
                                                     'type': 'photo',
                                                     'sizes': {'small': {'w': 620, 'h': 273, 'resize': 'fit'},
                                                               'medium': {'w': 620, 'h': 273, 'resize': 'fit'},
                                                               'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                                                               'large': {'w': 620, 'h': 273, 'resize': 'fit'}},
                                                     'source_status_id': 775413462788874240,
                                                     'source_status_id_str': '775413462788874240',
                                                     'source_user_id': 592843104,
                                                     'source_user_id_str': '592843104'}]}, 'extended_entities': {
            'media': [{'id': 775413458833637376, 'id_str': '775413458833637376', 'indices': [96, 119],
                       'media_url': 'http://pbs.twimg.com/media/CsLSbrfWAAAfFS0.jpg',
                       'media_url_https': 'https://pbs.twimg.com/media/CsLSbrfWAAAfFS0.jpg',
                       'url': 'https://t.co/9kX6sQKwzi', 'display_url': 'pic.twitter.com/9kX6sQKwzi',
                       'expanded_url': 'https://twitter.com/Geuze_F/status/775413462788874240/photo/1',
                       'type': 'photo', 'sizes': {'small': {'w': 620, 'h': 273, 'resize': 'fit'},
                                                  'medium': {'w': 620, 'h': 273, 'resize': 'fit'},
                                                  'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                                                  'large': {'w': 620, 'h': 273, 'resize': 'fit'}},
                       'source_status_id': 775413462788874240, 'source_status_id_str': '775413462788874240',
                       'source_user_id': 592843104, 'source_user_id_str': '592843104'}]},
         'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
         'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
         'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
         'user': {'id': 592843104, 'id_str': '592843104', 'name': 'François GEUZE', 'screen_name': 'Geuze_F',
                  'location': 'Lille, e-RH.org',
                  'description': "L'innovation au cœur des RH. #RH #SIRH #HRAnalytics #RelationsSociales f.geuze@e-rh.org",
                  'url': 'https://t.co/kxx1MEf2WU', 'entities': {'url': {'urls': [
                 {'url': 'https://t.co/kxx1MEf2WU', 'expanded_url': 'http://www.e-rh.org',
                  'display_url': 'e-rh.org', 'indices': [0, 23]}]}, 'description': {'urls': []}},
                  'protected': False, 'followers_count': 3970, 'friends_count': 1486, 'listed_count': 406,
                  'created_at': 'Mon May 28 14:15:11 +0000 2012', 'favourites_count': 3335, 'utc_offset': None,
                  'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 9306, 'lang': 'fr',
                  'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False,
                  'profile_background_color': 'FFFFFF',
                  'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/564144273/Capture_d__cran_2012-05-28___17.18.07.png',
                  'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/564144273/Capture_d__cran_2012-05-28___17.18.07.png',
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/2257483837/Capture_d__cran_2012-04-27___15.11.59_normal.png',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/2257483837/Capture_d__cran_2012-04-27___15.11.59_normal.png',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/592843104/1388580732',
                  'profile_link_color': '0084B4', 'profile_sidebar_border_color': 'FFFFFF',
                  'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
                  'profile_use_background_image': True, 'has_extended_profile': True, 'default_profile': False,
                  'default_profile_image': False, 'following': True, 'follow_request_sent': False,
                  'notifications': False}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
         'retweeted_status': {'created_at': 'Fri Sep 16 08:30:52 +0000 2016', 'id': 776699861970391040,
                              'id_str': '776699861970391040',
                              'text': 'Les nouvelles utopies managériales https://t.co/NJtn5ISY5l via @HubertLandier https://t.co/9kX6sQKwzi RT @Geuze_F',
                              'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [
                 {'screen_name': 'HubertLandier', 'name': 'Hubert Landier', 'id': 2799634401,
                  'id_str': '2799634401', 'indices': [63, 77]},
                 {'screen_name': 'Geuze_F', 'name': 'François GEUZE', 'id': 592843104, 'id_str': '592843104',
                  'indices': [105, 113]}], 'urls': [{'url': 'https://t.co/NJtn5ISY5l',
                                                     'expanded_url': 'http://www.e-rh.org/index.php/blogs/les-articles-du-blog/261-les-nouvelles-utopies-manageriales',
                                                     'display_url': 'e-rh.org/index.php/blog…',
                                                     'indices': [35, 58]}], 'media': [
                 {'id': 775413458833637376, 'id_str': '775413458833637376', 'indices': [78, 101],
                  'media_url': 'http://pbs.twimg.com/media/CsLSbrfWAAAfFS0.jpg',
                  'media_url_https': 'https://pbs.twimg.com/media/CsLSbrfWAAAfFS0.jpg',
                  'url': 'https://t.co/9kX6sQKwzi', 'display_url': 'pic.twitter.com/9kX6sQKwzi',
                  'expanded_url': 'https://twitter.com/Geuze_F/status/775413462788874240/photo/1', 'type': 'photo',
                  'sizes': {'small': {'w': 620, 'h': 273, 'resize': 'fit'},
                            'medium': {'w': 620, 'h': 273, 'resize': 'fit'},
                            'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                            'large': {'w': 620, 'h': 273, 'resize': 'fit'}}, 'source_status_id': 775413462788874240,
                  'source_status_id_str': '775413462788874240', 'source_user_id': 592843104,
                  'source_user_id_str': '592843104'}]}, 'extended_entities': {'media': [
                 {'id': 775413458833637376, 'id_str': '775413458833637376', 'indices': [78, 101],
                  'media_url': 'http://pbs.twimg.com/media/CsLSbrfWAAAfFS0.jpg',
                  'media_url_https': 'https://pbs.twimg.com/media/CsLSbrfWAAAfFS0.jpg',
                  'url': 'https://t.co/9kX6sQKwzi', 'display_url': 'pic.twitter.com/9kX6sQKwzi',
                  'expanded_url': 'https://twitter.com/Geuze_F/status/775413462788874240/photo/1', 'type': 'photo',
                  'sizes': {'small': {'w': 620, 'h': 273, 'resize': 'fit'},
                            'medium': {'w': 620, 'h': 273, 'resize': 'fit'},
                            'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                            'large': {'w': 620, 'h': 273, 'resize': 'fit'}}, 'source_status_id': 775413462788874240,
                  'source_status_id_str': '775413462788874240', 'source_user_id': 592843104,
                  'source_user_id_str': '592843104'}]},
                              'source': '<a href="http://www.hootsuite.com" rel="nofollow">Hootsuite</a>',
                              'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None,
                              'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
                              'in_reply_to_screen_name': None,
                              'user': {'id': 93874450, 'id_str': '93874450', 'name': 'Marion de Demos',
                                       'screen_name': 'Marion_Demos', 'location': 'France',
                                       'description': 'Community Manager #RH #management #recrutement #CPF',
                                       'url': 'http://t.co/simMG9FrRX', 'entities': {'url': {'urls': [
                                      {'url': 'http://t.co/simMG9FrRX',
                                       'expanded_url': 'http://www.demos.fr/fr/chaines-thematiques/responsable-formation/Pages/default.aspx',
                                       'display_url': 'demos.fr/fr/chaines-the…', 'indices': [0, 22]}]},
                                      'description': {'urls': []}},
                                       'protected': False, 'followers_count': 5179, 'friends_count': 1129,
                                       'listed_count': 494, 'created_at': 'Tue Dec 01 14:56:29 +0000 2009',
                                       'favourites_count': 504, 'utc_offset': 7200, 'time_zone': 'Paris',
                                       'geo_enabled': True, 'verified': False, 'statuses_count': 16143,
                                       'lang': 'fr', 'contributors_enabled': False, 'is_translator': False,
                                       'is_translation_enabled': False, 'profile_background_color': 'EBEBEB',
                                       'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/624213309525397504/dohK-p-O.jpg',
                                       'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/624213309525397504/dohK-p-O.jpg',
                                       'profile_background_tile': False,
                                       'profile_image_url': 'http://pbs.twimg.com/profile_images/755325139143782400/wr0j-IQb_normal.jpg',
                                       'profile_image_url_https': 'https://pbs.twimg.com/profile_images/755325139143782400/wr0j-IQb_normal.jpg',
                                       'profile_banner_url': 'https://pbs.twimg.com/profile_banners/93874450/1473077787',
                                       'profile_link_color': '990000', 'profile_sidebar_border_color': 'DFDFDF',
                                       'profile_sidebar_fill_color': 'F3F3F3', 'profile_text_color': '333333',
                                       'profile_use_background_image': True, 'has_extended_profile': False,
                                       'default_profile': False, 'default_profile_image': False, 'following': False,
                                       'follow_request_sent': False, 'notifications': False}, 'geo': None,
                              'coordinates': None, 'place': None, 'contributors': None, 'is_quote_status': False,
                              'retweet_count': 1, 'favorite_count': 0, 'favorited': False, 'retweeted': False,
                              'possibly_sensitive': False, 'possibly_sensitive_appealable': False, 'lang': 'fr'},
         'is_quote_status': False, 'retweet_count': 1, 'favorite_count': 0, 'favorited': False, 'retweeted': False,
         'possibly_sensitive': False, 'possibly_sensitive_appealable': False, 'lang': 'fr'},
        {'created_at': 'Fri Sep 16 08:46:41 +0000 2016', 'id': 776703844935933952, 'id_str': '776703844935933952',
         'text': 'RT @ericlemerdy: .@OCTOTechnology racheté, @ValtechTechno dissolu dans le digital. Que reste-il de 2008 ? Les challengers : @ZenikaIT et @X…',
         'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [
            {'screen_name': 'ericlemerdy', 'name': 'Eric Le Merdy', 'id': 17173023, 'id_str': '17173023',
             'indices': [3, 15]},
            {'screen_name': 'OCTOTechnology', 'name': 'OCTO Technology', 'id': 35731221, 'id_str': '35731221',
             'indices': [18, 33]},
            {'screen_name': 'ValtechTechno', 'name': 'Valtech Technology', 'id': 90410165, 'id_str': '90410165',
             'indices': [43, 57]},
            {'screen_name': 'ZenikaIT', 'name': 'Zenika', 'id': 77093727, 'id_str': '77093727',
             'indices': [124, 133]},
            {'screen_name': 'XebiaFr', 'name': 'Xebia France', 'id': 42832158, 'id_str': '42832158',
             'indices': [137, 140]}], 'urls': []},
         'source': '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
         'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
         'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
         'user': {'id': 30183861, 'id_str': '30183861', 'name': 'Matthieu Lux', 'screen_name': 'Swiip',
                  'location': 'Lyon, France',
                  'description': 'Dev & Trainer @ZenikaLyon, #Web & #JS fan and especially #React, #Redux, #Angular, #Gulp & #Node, administrator of @LyonJS. Co-Creator of @YeomanFountain',
                  'url': 'https://t.co/DKKg29NazQ', 'entities': {'url': {'urls': [
                 {'url': 'https://t.co/DKKg29NazQ', 'expanded_url': 'http://fountainjs.io/',
                  'display_url': 'fountainjs.io', 'indices': [0, 23]}]}, 'description': {'urls': []}},
                  'protected': False, 'followers_count': 1002, 'friends_count': 352, 'listed_count': 95,
                  'created_at': 'Fri Apr 10 08:02:06 +0000 2009', 'favourites_count': 264, 'utc_offset': 7200,
                  'time_zone': 'Paris', 'geo_enabled': False, 'verified': False, 'statuses_count': 2931,
                  'lang': 'en', 'contributors_enabled': False, 'is_translator': False,
                  'is_translation_enabled': False, 'profile_background_color': 'C0DEED',
                  'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/771887761/8e7af87287a0fc7c278ab57b31c7988d.jpeg',
                  'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/771887761/8e7af87287a0fc7c278ab57b31c7988d.jpeg',
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/565813885815369729/WwYOmeaE_normal.jpeg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/565813885815369729/WwYOmeaE_normal.jpeg',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/30183861/1377759057',
                  'profile_link_color': '0084B4', 'profile_sidebar_border_color': 'C0DEED',
                  'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
                  'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': False,
                  'default_profile_image': False, 'following': True, 'follow_request_sent': False,
                  'notifications': False}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
         'retweeted_status': {'created_at': 'Fri Sep 16 05:15:04 +0000 2016', 'id': 776650589702856704,
                              'id_str': '776650589702856704',
                              'text': '.@OCTOTechnology racheté, @ValtechTechno dissolu dans le digital. Que reste-il de 2008 ? Les challengers : @ZenikaIT et @XebiaFr !',
                              'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [
                 {'screen_name': 'OCTOTechnology', 'name': 'OCTO Technology', 'id': 35731221, 'id_str': '35731221',
                  'indices': [1, 16]},
                 {'screen_name': 'ValtechTechno', 'name': 'Valtech Technology', 'id': 90410165,
                  'id_str': '90410165', 'indices': [26, 40]},
                 {'screen_name': 'ZenikaIT', 'name': 'Zenika', 'id': 77093727, 'id_str': '77093727',
                  'indices': [107, 116]},
                 {'screen_name': 'XebiaFr', 'name': 'Xebia France', 'id': 42832158, 'id_str': '42832158',
                  'indices': [120, 128]}], 'urls': []},
                              'source': '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
                              'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None,
                              'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
                              'in_reply_to_screen_name': None,
                              'user': {'id': 17173023, 'id_str': '17173023', 'name': 'Eric Le Merdy',
                                       'screen_name': 'ericlemerdy', 'location': 'Vincennes',
                                       'description': 'Agile developer', 'url': 'https://t.co/VbVy9rpTzO',
                                       'entities': {'url': {'urls': [{'url': 'https://t.co/VbVy9rpTzO',
                                                                      'expanded_url': 'http://eric.lemerdy.name',
                                                                      'display_url': 'eric.lemerdy.name',
                                                                      'indices': [0, 23]}]},
                                                    'description': {'urls': []}}, 'protected': False,
                                       'followers_count': 691, 'friends_count': 186, 'listed_count': 61,
                                       'created_at': 'Tue Nov 04 23:38:45 +0000 2008', 'favourites_count': 204,
                                       'utc_offset': 7200, 'time_zone': 'Paris', 'geo_enabled': True,
                                       'verified': False, 'statuses_count': 2227, 'lang': 'fr',
                                       'contributors_enabled': False, 'is_translator': False,
                                       'is_translation_enabled': False, 'profile_background_color': '1A1B1F',
                                       'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/3303033/262776.png',
                                       'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/3303033/262776.png',
                                       'profile_background_tile': True,
                                       'profile_image_url': 'http://pbs.twimg.com/profile_images/378800000090174188/220893ebb02549a962abea175d0a40d0_normal.png',
                                       'profile_image_url_https': 'https://pbs.twimg.com/profile_images/378800000090174188/220893ebb02549a962abea175d0a40d0_normal.png',
                                       'profile_banner_url': 'https://pbs.twimg.com/profile_banners/17173023/1399815850',
                                       'profile_link_color': '2FC2EF', 'profile_sidebar_border_color': '181A1E',
                                       'profile_sidebar_fill_color': '252429', 'profile_text_color': '666666',
                                       'profile_use_background_image': True, 'has_extended_profile': False,
                                       'default_profile': False, 'default_profile_image': False, 'following': False,
                                       'follow_request_sent': False, 'notifications': False}, 'geo': None,
                              'coordinates': None, 'place': None, 'contributors': None, 'is_quote_status': False,
                              'retweet_count': 7, 'favorite_count': 3, 'favorited': False, 'retweeted': False,
                              'lang': 'fr'}, 'is_quote_status': False, 'retweet_count': 7, 'favorite_count': 0,
         'favorited': False, 'retweeted': False, 'lang': 'fr'},
        {'created_at': 'Fri Sep 16 08:02:39 +0000 2016', 'id': 776692761160478721, 'id_str': '776692761160478721',
         'text': 'RT @isacougnaud: #Entrepreneuriat : Les conseils des #startups à succès en termes de recrutement ! https://t.co/1Zsu0nCMsf #RH https://t.co…',
         'truncated': False, 'entities': {'hashtags': [{'text': 'Entrepreneuriat', 'indices': [17, 33]},
                                                       {'text': 'startups', 'indices': [53, 62]},
                                                       {'text': 'RH', 'indices': [123, 126]}], 'symbols': [],
                                          'user_mentions': [
                                              {'screen_name': 'isacougnaud', 'name': 'Isabelle COUGNAUD',
                                               'id': 565718534, 'id_str': '565718534', 'indices': [3, 15]}],
                                          'urls': [{'url': 'https://t.co/1Zsu0nCMsf',
                                                    'expanded_url': 'http://urlz.fr/45u7',
                                                    'display_url': 'urlz.fr/45u7', 'indices': [99, 122]}],
                                          'media': [{'id': 776691586298249216, 'id_str': '776691586298249216',
                                                     'indices': [139, 140],
                                                     'media_url': 'http://pbs.twimg.com/media/Csdc4fVXgAAPMMY.jpg',
                                                     'media_url_https': 'https://pbs.twimg.com/media/Csdc4fVXgAAPMMY.jpg',
                                                     'url': 'https://t.co/fDXnAmbxnD',
                                                     'display_url': 'pic.twitter.com/fDXnAmbxnD',
                                                     'expanded_url': 'https://twitter.com/isacougnaud/status/776691659706949632/photo/1',
                                                     'type': 'photo',
                                                     'sizes': {'large': {'w': 620, 'h': 402, 'resize': 'fit'},
                                                               'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                                                               'small': {'w': 620, 'h': 402, 'resize': 'fit'},
                                                               'medium': {'w': 620, 'h': 402, 'resize': 'fit'}},
                                                     'source_status_id': 776691659706949632,
                                                     'source_status_id_str': '776691659706949632',
                                                     'source_user_id': 565718534,
                                                     'source_user_id_str': '565718534'}]}, 'extended_entities': {
            'media': [{'id': 776691586298249216, 'id_str': '776691586298249216', 'indices': [139, 140],
                       'media_url': 'http://pbs.twimg.com/media/Csdc4fVXgAAPMMY.jpg',
                       'media_url_https': 'https://pbs.twimg.com/media/Csdc4fVXgAAPMMY.jpg',
                       'url': 'https://t.co/fDXnAmbxnD', 'display_url': 'pic.twitter.com/fDXnAmbxnD',
                       'expanded_url': 'https://twitter.com/isacougnaud/status/776691659706949632/photo/1',
                       'type': 'photo', 'sizes': {'large': {'w': 620, 'h': 402, 'resize': 'fit'},
                                                  'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                                                  'small': {'w': 620, 'h': 402, 'resize': 'fit'},
                                                  'medium': {'w': 620, 'h': 402, 'resize': 'fit'}},
                       'source_status_id': 776691659706949632, 'source_status_id_str': '776691659706949632',
                       'source_user_id': 565718534, 'source_user_id_str': '565718534'}]},
         'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
         'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
         'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
         'user': {'id': 1269648812, 'id_str': '1269648812', 'name': 'Le Lab RH', 'screen_name': 'LeLabRH',
                  'location': 'Paris, France',
                  'description': "L'association de promotion et de soutien de l'#innovation #RH // #Startups #France #lelabrh // Le futur est à propos de #UXyourlife",
                  'url': 'http://t.co/Vcxm4LhMzC', 'entities': {'url': {'urls': [
                 {'url': 'http://t.co/Vcxm4LhMzC', 'expanded_url': 'http://www.lab-rh.com',
                  'display_url': 'lab-rh.com', 'indices': [0, 22]}]}, 'description': {'urls': []}},
                  'protected': False, 'followers_count': 3597, 'friends_count': 934, 'listed_count': 568,
                  'created_at': 'Fri Mar 15 12:46:39 +0000 2013', 'favourites_count': 2154, 'utc_offset': 7200,
                  'time_zone': 'Paris', 'geo_enabled': False, 'verified': False, 'statuses_count': 4946,
                  'lang': 'fr', 'contributors_enabled': False, 'is_translator': False,
                  'is_translation_enabled': False, 'profile_background_color': '134057',
                  'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/816147458/7606319f79aeb2f63cbf8397d8bfe038.gif',
                  'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/816147458/7606319f79aeb2f63cbf8397d8bfe038.gif',
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/669830717040381953/Bu36cksF_normal.png',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/669830717040381953/Bu36cksF_normal.png',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1269648812/1467799588',
                  'profile_link_color': '3B94D9', 'profile_sidebar_border_color': 'FFFFFF',
                  'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
                  'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': False,
                  'default_profile_image': False, 'following': True, 'follow_request_sent': False,
                  'notifications': False}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
         'retweeted_status': {'created_at': 'Fri Sep 16 07:58:16 +0000 2016', 'id': 776691659706949632,
                              'id_str': '776691659706949632',
                              'text': '#Entrepreneuriat : Les conseils des #startups à succès en termes de recrutement ! https://t.co/1Zsu0nCMsf #RH https://t.co/fDXnAmbxnD',
                              'truncated': False, 'entities': {
                 'hashtags': [{'text': 'Entrepreneuriat', 'indices': [0, 16]},
                              {'text': 'startups', 'indices': [36, 45]}, {'text': 'RH', 'indices': [106, 109]}],
                 'symbols': [], 'user_mentions': [], 'urls': [
                     {'url': 'https://t.co/1Zsu0nCMsf', 'expanded_url': 'http://urlz.fr/45u7',
                      'display_url': 'urlz.fr/45u7', 'indices': [82, 105]}], 'media': [
                     {'id': 776691586298249216, 'id_str': '776691586298249216', 'indices': [110, 133],
                      'media_url': 'http://pbs.twimg.com/media/Csdc4fVXgAAPMMY.jpg',
                      'media_url_https': 'https://pbs.twimg.com/media/Csdc4fVXgAAPMMY.jpg',
                      'url': 'https://t.co/fDXnAmbxnD', 'display_url': 'pic.twitter.com/fDXnAmbxnD',
                      'expanded_url': 'https://twitter.com/isacougnaud/status/776691659706949632/photo/1',
                      'type': 'photo', 'sizes': {'large': {'w': 620, 'h': 402, 'resize': 'fit'},
                                                 'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                                                 'small': {'w': 620, 'h': 402, 'resize': 'fit'},
                                                 'medium': {'w': 620, 'h': 402, 'resize': 'fit'}}}]},
                              'extended_entities': {'media': [
                                  {'id': 776691586298249216, 'id_str': '776691586298249216', 'indices': [110, 133],
                                   'media_url': 'http://pbs.twimg.com/media/Csdc4fVXgAAPMMY.jpg',
                                   'media_url_https': 'https://pbs.twimg.com/media/Csdc4fVXgAAPMMY.jpg',
                                   'url': 'https://t.co/fDXnAmbxnD', 'display_url': 'pic.twitter.com/fDXnAmbxnD',
                                   'expanded_url': 'https://twitter.com/isacougnaud/status/776691659706949632/photo/1',
                                   'type': 'photo', 'sizes': {'large': {'w': 620, 'h': 402, 'resize': 'fit'},
                                                              'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                                                              'small': {'w': 620, 'h': 402, 'resize': 'fit'},
                                                              'medium': {'w': 620, 'h': 402, 'resize': 'fit'}}}]},
                              'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                              'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None,
                              'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
                              'in_reply_to_screen_name': None,
                              'user': {'id': 565718534, 'id_str': '565718534', 'name': 'Isabelle COUGNAUD',
                                       'screen_name': 'isacougnaud', 'location': 'Nantes',
                                       'description': 'Chargée de #communication digitale @MinesNantes pour 1 an.  Passionnée. #innovation | #startup | #digital | #web | #CM | #socialmedia | #i4emploi',
                                       'url': 'https://t.co/f7poG7g2Lb', 'entities': {'url': {'urls': [
                                      {'url': 'https://t.co/f7poG7g2Lb',
                                       'expanded_url': 'https://fr.linkedin.com/in/isabellecougnaud',
                                       'display_url': 'fr.linkedin.com/in/isabellecou…', 'indices': [0, 23]}]},
                                      'description': {'urls': []}},
                                       'protected': False, 'followers_count': 13906, 'friends_count': 7389,
                                       'listed_count': 369, 'created_at': 'Sat Apr 28 20:27:04 +0000 2012',
                                       'favourites_count': 1133, 'utc_offset': 7200, 'time_zone': 'Paris',
                                       'geo_enabled': True, 'verified': False, 'statuses_count': 250, 'lang': 'fr',
                                       'contributors_enabled': False, 'is_translator': False,
                                       'is_translation_enabled': False, 'profile_background_color': '000000',
                                       'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                                       'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                                       'profile_background_tile': False,
                                       'profile_image_url': 'http://pbs.twimg.com/profile_images/714835223578546176/Hzp6T7wR_normal.jpg',
                                       'profile_image_url_https': 'https://pbs.twimg.com/profile_images/714835223578546176/Hzp6T7wR_normal.jpg',
                                       'profile_banner_url': 'https://pbs.twimg.com/profile_banners/565718534/1442857102',
                                       'profile_link_color': 'DD2E44', 'profile_sidebar_border_color': '000000',
                                       'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000',
                                       'profile_use_background_image': False, 'has_extended_profile': True,
                                       'default_profile': False, 'default_profile_image': False, 'following': False,
                                       'follow_request_sent': False, 'notifications': False}, 'geo': None,
                              'coordinates': None, 'place': None, 'contributors': None, 'is_quote_status': False,
                              'retweet_count': 7, 'favorite_count': 6, 'favorited': False, 'retweeted': False,
                              'possibly_sensitive': False, 'possibly_sensitive_appealable': False, 'lang': 'fr'},
         'is_quote_status': False, 'retweet_count': 7, 'favorite_count': 0, 'favorited': False, 'retweeted': False,
         'possibly_sensitive': False, 'possibly_sensitive_appealable': False, 'lang': 'fr'}
    ]